### PR TITLE
bump helm version to 3.5.3 and add wait-for-jobs arg

### PR DESCRIPTION
**Pull request by bmbferreira**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

The motivation of this PR is to add the new argument "wait-for-jobs" for [helm install](https://helm.sh/docs/helm/helm_install/) and [upgrade](https://helm.sh/docs/helm/helm_upgrade/) that solves the issues described on [#5948](https://github.com/helm/helm/issues/5948) and introduced on version 3.5.0 on the PR [#8363](https://github.com/helm/helm/pull/8363).

### Description

To be able to add the new flag wait-for-jobs I had to also update the helm version to the latest version.

### CODE REVIEW

**Comment by bmbferreira** [comment]
@KyleTryon @felicianotech 
sorry to bother you, but can you give some feedback on this PR? Thanks!

**Comment by gmemstr** [comment]
@bmbferreira Note that updating the version in `.circleci/config.yml` won't actually affect the orb itself. Not sure if this is intentional.

**Comment by bmbferreira** [comment]
> @bmbferreira Note that updating the version in `.circleci/config.yml` won't actually affect the orb itself. Not sure if this is intentional.

I know, but it was intentional to use a more recent version.

**Comment by brivu** [comment]
Hey @bmbferreira, I just added this in PR #67. Thanks for contributing!

**Pull request closed without merging**
