### PR TITLE
fixed vars handling

### PR DESCRIPTION
**Pull request by tymik**
Signed-off-by: Jan Tymiński <jan.tyminski@netguru.com>

### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

Fix for environment variables evaluation passed to orb parameters - issue similar like in #50 / #52

### Description

I have found a problem with `namespace` passed as an environment variable being problematic, where it worked passed as a literal string. I checked the source of the orb and the merged PRs and found that the issue was resolved in #50 / #52 but just for one of the paremeters.
I did a review of all the parameters in all the commands in this orb and amended accordingly.

### CODE REVIEW

**Comment by tymik** [comment]
@brivu @KyleTryon or whoever else might do the review, please review this PR.

**Comment by tymik** [comment]
anyone?

**Comment by mareksuscak** [comment]
Using `eval` is a breaking change, the approach needs to be rethought here, see https://github.com/CircleCI-Public/helm-orb/issues/58

**Comment by brivu** [comment]
Hey @tymik, 

We've taken care of this issue with PR #68. Instead of using `eval`, we've implemented `circleci env subst` to handle the substitution of strings. 

Thanks for contributing! 
Brian

**Pull request closed without merging**
