### PR TITLE
Interp envs

### LINKED ISSUE #50: values-to-override can't handle environment variables
### Orb version

2.0.0

### What happened

The parameter values-to-override can't handle environment variables anymore in the new orb version.

### Expected behavior

I used to pass environment vars like this:
`values-to-override: image.tag=0.0.${CIRCLE_SHA1},image.repository=${AWS_ECR_ACCOUNT_URL}/<< parameters.repository >>`,
and get the following output in the chart:
```
image:
  repository: ACCOUNT.dkr.ecr.REGION.amazonaws.com/my_repo
  tag: 0.0.RANDOM_SHA1

```
### What's broken

Instead, I'm getting this now:
```
image:
  repository: $AWS_ECR_ACCOUNT_URL/my_repo
  tag: 0.0.$CIRCLE_SHA1

```
I tried manipulating the strings in a lot of variations, and nothing helped.

I'd be glad to get a quick response, I can even contribute if needed.
This currently takes down my deployments and I will probably revert the orb version to 1.2.0 again until a fix will be available.

### PR DESCRIPTION
**Pull request by KyleTryon**
### Checklist

- [ x ] All new jobs, commands, executors, parameters have descriptions
- [ x ] Examples have been added for any significant new features
- [ x ] README has been updated, if necessary

### Motivation, issues

* Fixes #50 

### Description

Interpolates the environment variables in the `VALUES_TO_OVERRIDE` and `VALUES` parameter environment variables.

### CODE REVIEW

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/helm?version=dev:beb231e48c2e2d1bfd6f8a39a617099647b32dc9

**Review by brivu — APPROVED** [review]
Looks good!

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/helm?version=dev:d6dfabc762c6ae4696ec8d89740b200668a7d3a0

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/helm?version=dev:d6dfabc762c6ae4696ec8d89740b200668a7d3a0

**Comment by orb-publisher** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/helm?version=2.0.1

**Comment by jverce** [comment]
This is actually backwards incompatible, since users specifying a path for a values file will now get an error like this:
```
/bin/bash: line 31: deployments/helm/values.yaml: Permission denied
```

The problem is that the script is taking a path to a YAML file, and tries to evaluate it as an environment variable.
A possible fix on the user's end is to add an extra step in their process that exports the name of the values file to an environment variable, and replace the values file path with the name of that environment variable, which doesn't quite align to the documented behaviour of the `values` parameter:
> specify values in a YAML file or a URL

**Pull request merged**
